### ISSUE TITLE
Packaging with cx_Freeze: AttributeError: 'module' object has no attribute '__file__'

### ISSUE THREAD

**Issue by SergioVernis** [jarvisteach/appJar#159] opened 2017-05-04 19:35 UTC
Hello:

Packaging with cx_Freeze: AttributeError: 'module' object has no attribute '__file__'

Full Traceback:
Traceback (most recent call last):
  File "c:\python\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>  exec(code, m.__dict__)
  File "C:\Programming\X.py", line 48, in <module>    app = appJar.gui()
  File "c:\python\Python34\lib\site-packages\appJar\appjar.py", line 415, in __init__  self.exe_file = os.path.basename(theMain.__file__)
AttributeError: 'module' object has no attribute '__file__'

I workaround this changing file appjar.py lines 413 414:

From:
`self.exe_file = os.path.basename(theMain.__file__)`
`self.exe_loc = os.path.dirname(theMain.__file__)`

To:
`self.exe_file = os.path.basename(__file__)`
`self.exe_loc = os.path.dirname(__file__)`

This solution works well in python normal and packaged with cx_Freeze.

Thanks for your work.

Sergio

**Comment by jarvisteach** [comment] 2017-05-24 22:20
Hi @SergioVernis, thanks for this! Issues with the code you mentioned have already been raised in issue #131 - it breaks appJar when run in interactive mode.

So, I think the two are related. I need to do a bit more work on this - and make sure the solution used works in all scenarios. I'll get back to you...

**Comment by jarvisteach** [comment] 2017-05-26 20:10
Closing as duplicate of #131

**Closed by jarvisteach** 2017-05-26 20:10 UTC
Labels: bug
