### ISSUE TITLE
matplotlib loosing axis labels and legend after update

### ISSUE THREAD

**Issue by gh0st42** [jarvisteach/appJar#242] opened 2017-09-02 18:52 UTC
After updating a plot xlabel, ylabel and legend is lost. Since updatePlot() does not return an axis object one cannot add the information again.

The following code triggers the bug:

```
from numpy import sin, pi, arange
from appJar import gui

def press(btn):
    x = arange(0.0, 3.0, 0.01)
    y = sin(3*pi*x)
    a = app.updatePlot("p1", x, y)
    print a

x = arange(0.0, 3.0, 0.01)
y = sin(2*pi*x)

app = gui()
axes = app.addPlot("p1", x, y)
axes.legend(['key data'])
axes.set_xlabel("bla")
app.addButton("Update", press)
app.go()
```

**Comment by jarvisteach** [comment] 2017-09-02 19:47
Calling `app.updatePlot()` modifies the existing axes - so its the same axes object you already have.
However, I will modify `.updatePlot(0` to return the axes object as well.

The issue is that the canvas needs redrawing.

If you modify the function to include:
```
axes.legend(['key data'])
axes.set_xlabel("bla")
```

Then they are added to the plot, but not shown until the canvas is redrawn - try resizing it to achieve that.

To do it programatically, you'll need to force a redraw, after updating the axes: `app.refreshPlot("p1")`

**Comment by jarvisteach** [comment] 2017-09-02 19:51
That's quite a mouthful! So you might want to put that bit of code in its own function:
```
def showLabels(axes):
    axes.legend(['key data'])
    axes.set_xlabel("bla")
    app.refreshPlot("p1")
```
You can then call that from both places.

FYI - the initial label/legend only show as they're added before the GUI is drawn, I'll update the docs to make this more clear.

**Comment by jarvisteach** [comment] 2017-09-02 19:55
PS. the matplotlib support is very rudimentary - there are various difficulties getting tkinter and matplotlib to play together nicely - I *think* I've overcome them...

Do let me know how you get on, any issues you come across or features you'd like - I don't have too much experience with it myself, and haven't seen many people use it in appJar.

**Comment by jarvisteach** [comment] 2017-09-02 20:10
This is the updated code I'm going to put in the example (I borrowed bits from yours):
```
from numpy import sin, pi, arange
from appJar import gui 
import random

def getXY():
    x = arange(0.0, 3.0, 0.01)
    y = sin(random.randint(1,10)*pi*x)
    return x,y 

def press(btn):
    app.updatePlot("p1", *getXY())
    showLabels()

def showLabels():
    axes.legend(['The curve'])
    axes.set_xlabel("X Axes")
    axes.set_ylabel("Y Axes")
    app.refreshPlot("p1")

app = gui()
axes = app.addPlot("p1", *getXY())
showLabels()
app.addButton("Update", press)
app.go()
```

**Comment by gh0st42** [comment] 2017-09-02 20:29
Okay thanks for the quick workaround! 
Preserving the axes information when calling updatePlot() would be preferable but having a function to get the axes object for an existing plot would also be okay. Having many global variables or managing all of them in your main program does not seem like good coding practice.

But for a "beta widget" it is really cool to have such a powerful plotting function available in an easy UI lib such as appJar!

**Comment by jarvisteach** [comment] 2017-09-02 20:54
I'll look into preserving the axes information - like I said, don't really know much about it.

There is a fairly generic function for getting widgets, which will then give you access to the axes object:
`axes = app.getWidget(app.PLOT, "p1").axes`

That will save you having to keep a reference to the axes...

**Comment by jarvisteach** [comment] 2017-09-02 21:08
At the moment, `app.updatePlot()` really doesn't do much - it just calls 2 matplotlib functions: `clear()` & `plot()` followed by a canvas refresh.

I guess the `clear()` removes the labels/legend as well as the plot.

If this isn't the desired result, then you can perform whichever actions you'd like directly on the axes - just make sure you call `app.refreshPlot()` at the end to redraw the canvas holding the plot.

I'll keep digging into matplotlib on how to persist the labels and change the plot - let me know if you know how to do this already...

**Comment by jarvisteach** [comment] 2017-09-03 12:16
I've looked into this a bit - there are **LOTS** of settings a user could configure on the axes.

I can see a way to `get` the title & x/y labels, and therefore set them again when the axes is updated, I'm struggling to get the legend to work though.

I actually think this might be a feature I don't want. I don't think appJar should be doing any of the work for matplotlib. I've set it up so tkinter & matplotlib play nicely together, and given a way to add a widget containing a plot, the rest should be down to the user.

If the user is changing the plot, then the title/labels/legend may need to be changed as well. If not, then it's not a big job to set them again.

I might provide a boolean flag (defaulting to False) on `.updatePlot()` that allows the user to request the labels & title are kept (and legend if I can work it out) and leave it at that.

**Comment by jarvisteach** [comment] 2017-09-03 12:18
I've also noticed that the code for Plots seems to be repeated in appJar - that needs to be fixed.

**Comment by jarvisteach** [comment] 2017-09-17 09:46
Now have a flag to 'retain' labels - but doesn't get the legend.

**Comment by jarvisteach** [comment] 2017-10-14 11:04
Closing, see #267

**Closed by jarvisteach** 2017-10-14 11:04 UTC
Labels: question
