### ISSUE TITLE
labelFrame title gap using hideTitle

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#272] opened 2017-10-15 10:39 UTC
If you use ttk and set hideTitle=True on a labelFrame the title is replaced with a gap.

**Comment by jarvisteach** [comment] 2017-10-15 12:15
Unable to reproduce on Mac.

Setting that flag changes the LabelFrame's label to be an empty string. Maybe it's keeping the space that was used before. I might need to look into changing the LabelFrame's creation somehow...

**Comment by mpmc** [comment] 2017-10-15 13:26
Ok I figured it out. it's theme specific.

clam = No gap
default/alt = gap

Here's some code (that I'm currently working on) that you can try.

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  hs602util.py
#
#  Copyright 2017 Mark Clarkstone <git@markclarkstone.co.uk>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#
import gettext
import uuid
import appJar

# Setup gettext.
gettext.install('Hs602util')

class Hs602util(appJar.gui):
    """Simple HS602 utility using appJar."""
    def __init__(self):
        super().__init__()
        self.useTtk()
        self.setTtkTheme('clam')
        self.main_win()

    def lang(self, key):
        """Return string value of the requested key in values.

        :param key: key of the value you want.
        """
        values = {
            'main_title': _('HS602 Utility'),
            'connection_frm': _('Connect to Device'),
            'addr_lbl': _('Device address'),
            'discover_btn': _('Discover'),
            'settings_frm': _('Connection Settings'),
            'tcp_port_lbl': _('TCP port'),
            'udp_port_lbl': _('UDP port'),
            'timeout_lbl': _('Timeout'),
            'connect_btn': _('Connect'),
        }
        value = None
        try:
            value = values[key]
        except KeyError:
            pass
        return str(value or uuid.uuid4())

    def main_win(self):
        """Main window."""

        # Window settings.
        self.setTitle(self.lang('main_title'))

        # Connection frame.
        with self.labelFrame(self.lang('connection_frm'), 
                             hideTitle=False):
            self.setPadding(5, 5)
            self.setSticky('nesw')

            # Widgets.
            self.addLabel('addr_lbl', self.lang('addr_lbl'), 0, 0, 1)
            self.addEntry('dev_addr', 0, 1)
            self.addButton(self.lang('discover_btn'), None, 0, 2)
            self.addButton(self.lang('connect_btn'), None, 1, 2)
            
            self.setLabelAlign('addr_lbl', 'center')

            # Connection settings frame.
            with self.labelFrame(self.lang('settings_frm'), 1, 0, 2):
                self.setSticky('nesw')
                self.setInPadding(5, 5)
                self.setPadding(5, 5)

                # Widgets.
                self.addLabel('tcp_port_lbl', self.lang('tcp_port_lbl'),
                              1, 1)
                self.addLabel('udp_port_lbl', self.lang('udp_port_lbl'),
                              2, 1)
                self.addLabel('timeout_lbl', self.lang('timeout_lbl'),
                              3, 1)
                self.addNumericEntry('adv_tcp', 1, 2)
                self.addNumericEntry('adv_udp', 2, 2)
                self.addNumericEntry('adv_timeout', 3, 2)

                self.setLabelAlign('tcp_port_lbl', 'center')
                self.setLabelAlign('udp_port_lbl', 'center')
                self.setLabelAlign('timeout_lbl', 'center')

app = Hs602util()
app.go()
```
The excessive padding, sticking after each frame is because ttk expects them to be set for each. :disappointed:

**Comment by jarvisteach** [comment] 2018-01-17 20:52
Closing this, as no actions outstanding.

**Closed by jarvisteach** 2018-01-17 20:52 UTC
Labels: bug
