### ISSUE TITLE
GUI shows on Windows 10 but not on macOS 10.14

### ISSUE THREAD

**Issue by karkraeg** [jarvisteach/appJar#588] opened 2019-08-26 08:26 UTC
The appjar GUI of my program shows on Windows 10 (and Ubuntu) but not on macOS 10.14 – it stays blank here. Is this a known bug/does anybody else has similar problems? I had it working but now it just stays white:
<img width="500" alt="Screenshot of python (26-08-19, 10-25-14)" src="https://user-images.githubusercontent.com/8436596/63676695-ce116800-c7eb-11e9-84db-0b58abda30a9.png">

I’m asking this because reverting changes until I have the GUI back seems tiresome and perhaps there is something known about this or can point me in some sort of Debugging mode for appJar.

I’m using appJar Version 0.94.0

Thanks!

**Comment by naurojr** [comment] 2019-08-26 12:58
Did you try to switch from Dark mode to regular mode? There is a known issue with using Dark Mode.

**Comment by karkraeg** [comment] 2019-08-26 14:13
I tried just now, looks the same:

<img width="612" alt="Screenshot" src="https://user-images.githubusercontent.com/8436596/63697054-6293be80-c81c-11e9-868d-8b834f4d73e0.png">

**Comment by jarvisteach** [comment] 2019-09-25 19:51
No known issues on Mac OS 10.14 - could you post some code that reproduces this error?

**Comment by jarvisteach** [comment] 2019-10-12 18:28
Closing this, as can't reproduce.

**Closed as completed by jarvisteach** 2019-10-12 18:28 UTC
Labels: can't reproduce, platform
