### ISSUE TITLE
Unable to set file entry value

### ISSUE THREAD

**Issue by pg-doceapower** [jarvisteach/appJar#487] opened 2018-07-19 10:06 UTC
Hello,

fileEntry returns the absolute path picked by the user.  in my caseI would like to display this path relative to the project location (another filed in the application). with python it seems easy to calculate relative path to a known origin however I'm unable to set the fileEntry with the relative path with setEntry("myFileEntry",relativePath) 

any idea?

Thanks and sorry for the beginner's question

**Comment by jarvisteach** [comment] 2018-07-23 16:17
@pg-doceapower - I've had a quick look at this, and it's definitely possible to put your own data into a file entry. However, I also noticed that, it doesn't work when done after the dialog closes.

I've seen this kind of issue before, where the GUI change the change we're making is conflicting with the change the caused by closing the file dialog, resulting in unexpected behaviour.

The best solution is to queue the change to occur at a later date:

```python
from appJar import gui 

def press():
    app.setEntry('fn', app.entry('New text')) 
def change():
    val = app.entry("fn").rsplit('/', 1)[-1]
    app.queueFunction(app.setEntry, 'fn', val, callFunction=False)

with gui() as app:
    app.entry('fn', kind='file', change=change)
    app.button("press", press)
    app.entry("New text", label=True)
```

**Comment by pg-doceapower** [comment] 2018-07-31 20:27
hello and thanks for the quick investigation. I'll experiment and report
back. wish I was as fast as you are...

**Comment by jarvisteach** [comment] 2018-08-21 21:01
Closing - added to backlog #527

**Closed by jarvisteach** 2018-08-21 21:01 UTC
Labels: enhancement, question
