### ISSUE TITLE
Matplotlib issues - 'FigureCanvasTkAgg' object has no attribute 'show'

### ISSUE THREAD

**Issue by simonjharris** [jarvisteach/appJar#551] opened 2018-11-04 11:38 UTC
## Context
---
I wanted to started testing matplotlib integration with appJar, unfortunately when I tried to run the example code from http://appjar.info/outputWidgets/#matplotlib, I get error messages.

## Any error messages produced by appJar
---
Traceback (most recent call last):
  File "/Users/simon/PycharmProjects/data_analysis/gui_graphs.py", line 23, in <module>
    axes = app.addPlot("p1", *getXY())
  File "/Users/simon/PycharmProjects/TestProject/venv/lib/python3.7/site-packages/appJar/appjar.py", line 6392, in addPlot
    canvas, fig = self._addPlotFig(title, row, column, colspan, rowspan, width, height)
  File "/Users/simon/PycharmProjects/TestProject/venv/lib/python3.7/site-packages/appJar/appjar.py", line 6416, in _addPlotFig
    canvas.show()
AttributeError: 'FigureCanvasTkAgg' object has no attribute 'show'

## Version Information
---
Tested on mac with python 3.7.0 and ubuntu with 3.6.0. Matplotlib version 3.0.1, appJar 0.93.

**Comment by pjgao** [comment] 2018-11-09 03:51
try function `draw` instead

**Comment by Mr-Jarvis** [comment] 2018-11-09 23:01
This has been resolved in the next release - as @pjgao mentions, it should be using `draw()`

**Comment by jarvisteach** [comment] 2018-11-09 23:05
Duplicate of #549

**Closed by jarvisteach** 2018-11-09 23:05 UTC

**Comment by tnsolley** [comment] 2019-02-14 14:27
Running into this issue myself. Can you be more specific on what you mean by "use function `draw` instead"?

**Comment by tnsolley** [comment] 2019-02-14 14:30
Note; actually making that change throws a Tkinter error;
```
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
===== RESTART: //cotofs01/tsolley$/Coto/Vibration_tester/test_layout.py =====
2019-02-14 09:26:35,105 appJar:ERROR [Line 107->1706/__exit__]: ContextManager failed: cannot use geometry manager pack inside .!canvasdnd.!widgetcontainer.!tabbedframe.!framestack.!frame2.!labelframe which already has slaves managed by grid
Traceback (most recent call last):
  File "//cotofs01/tsolley$/Coto/Vibration_tester/test_layout.py", line 99, in <module>
    axes = app.addPlot("p1", *getXY())
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\appJar\appjar.py", line 6392, in addPlot
    canvas, fig = self._addPlotFig(title, row, column, colspan, rowspan, width, height)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\appJar\appjar.py", line 6419, in _addPlotFig
    canvas._tkcanvas.pack(side=TOP, fill=BOTH, expand=1)
  File "C:\Program Files (x86)\Python37-32\lib\tkinter\__init__.py", line 2143, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager pack inside .!canvasdnd.!widgetcontainer.!tabbedframe.!framestack.!frame2.!labelframe which already has slaves managed by grid
>>> 
```
