### ISSUE TITLE
Calling menu

### ISSUE THREAD

**Issue by maestroi** [jarvisteach/appJar#79] opened 2017-01-02 13:14 UTC
Calling `.addMenu(menu, function, shortcut=None, underline=-1)`
with defined function will call function on startup on application not on click.

**Comment by jarvisteach** [comment] 2017-01-05 01:12
I'm unable to reproduce this - could you let me know what platform/python version you're using?

The .addMenu function uses the same method to link functions to widgets that everything else does, and they all seem to work fine, so I can't see where this would fall down.

**Comment by jarvisteach** [comment] 2017-02-25 20:25
Closing as can't reproduce

**Closed by jarvisteach** 2017-02-25 20:25 UTC
