### ISSUE TITLE
app.addScrolledTextArea() not scaling horizontally with LabelFrame(sticky='new')

### ISSUE THREAD

**Issue by tnsolley** [jarvisteach/appJar#542] opened 2018-10-10 20:29 UTC
# Bug Report
---

## Context
---
Messing with the <showcase.py> file and testing the addition of a few bits, including the Scrolled Text Area (which I would like to use in a future app).

## Expected Behaviour
---
Expected for the `app.addScrolledTextArea(colspan=___)` to be of width 'colspan'.

## Actual Behaviour
---
The Scrolled Text Area does not change horizontal width, even when inside of a LabelFrame that should scale (sticky='news').

## Any error messages produced by appJar
---
N/A

## Sample code, demonstrating the issue
---
`with app.tab("HW", bg="slategrey", sticky="news"):
      with app.labelFrame("HW Feedback"):
        app.label("foo4", "Feedback:", row=0, column=0, colspan=1, rowspan=1)
        app.addScrolledTextArea("lb4", row=1, column=0, colspan=1, rowspan=1)
        #app.addHorizontalSeparator(row=31, column=0, colspan=1, rowspan=1)
        app.separator(row=31, column=0, colspan=1, sticky='news')
        app.buttons(["Run","Retest","Quit HW"], s3, row=32, column=0)
        app.buttons(["To Results"], t4, row=33, column=0)
      # End with-statement
    # End with-statement` 

## What steps are needed to reproduce the bug
---
Add above code as tab-object within the <showcase.py> file, e.g. after `with app.tab("Properties"):`.

## Version Information
---
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
Windows 10
AppJar 0.9.3

**Comment by tnsolley** [comment] 2018-10-15 14:42
Tried replacing all calls of `app.addScrolledTextArea()` with `app._textMaker(title, "scroll", row, column, colspan=2, rowspan, sticky="news")`, no change to the GUI. The "sticky" parameter does not seem to have taken-effect.

**Comment by tnsolley** [comment] 2018-10-22 13:55
@jarvisteach I was able to get the same results by modifying the LabelFrame as well.

**Comment by jarvisteach** [comment] 2020-03-19 22:49
Going to close this as 'not a bug'. The docs definitely state that LabelFrames have a `w` stickiness. See here: http://appjar.info/pythonWidgetGrouping/#label-frame

**Closed by jarvisteach** 2020-03-19 22:49 UTC
Labels: question
