### ISSUE TITLE
Page Scrolling in Text Widgets?

### ISSUE THREAD

**Issue by abhijit-dey** [jarvisteach/appJar#337] opened 2018-01-05 04:56 UTC
How to add page scrolling when, for e.g., a label has more text than what the laptop window height can show?

**Comment by jarvisteach** [comment] 2018-01-05 10:56
You could try putting it in a [scroll pane](http://appjar.info/pythonWidgetGrouping/#scroll-pane)

**Comment by abhijit-dey** [comment] 2018-01-05 18:42
Tried putting Label in scroll pane.

When I try to scroll using trackpad in Mac, I get this error:
2018-01-06 00:10:35,532 appJar:ERROR [Line 215->1884/go]: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/appJar/appjar.py", line 1879, in go
    self.topLevel.mainloop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1277, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by jarvisteach** [comment] 2018-01-05 19:59
Haven't seen that one before!

I do most of my development on a Mac and have no problems.

I've done a quick google, and there is an issue with python/tkinter: https://stackoverflow.com/questions/16995969/inertial-scrolling-in-mac-os-x-with-tkinter-and-python

Could you post your version of python/tkinter/appJar and a snippet of code that will allow me to reproduce the problem? (if you run it with the `-v` flag it should tell you: `python test.py -v`)

**Comment by abhijit-dey** [comment] 2018-01-06 03:18
version info:
--------------
appJar: 0.82.1 Python: 3.6.1 TCL: 8.5, TK: 8.5 Platform: Darwin pid: 14960
locale: None

Code:
--------
from appJar import gui

app = gui("appJar Testing")
#app.setStretch("none")
#app.setFont(15)
#app.setGeometry("600x400")

app.startScrollPane("sp1")
for x in range(0,40):
    label_name = "l" + str(x)
    app.addLabel(label_name, "This is inside scroll pane.")
app.stopScrollPane()

app.go()

**Comment by jarvisteach** [comment] 2018-01-06 23:37
I can't reproduce this on my mac - it's not an issue with appJar, but rather a python/tkinter/tcl issue.

You could try upgrading your python installation.

Or, if you want to try editing appJar, you could try one of the workarounds from stackOverflow, this is one suggestion:
```
        # start the main loop
        while True: 
            try:  
                self.topLevel.mainloop()
            except(KeyboardInterrupt, SystemExit) as e: 
                self.debug("appJar stopped through ^c or exit()")
                self.stop()
                break 
            except UnicodeDecodeError:
                pass  
            except Exception as e: 
                self.exception(e)
                self.stop()
                break 
```

That needs to replace the current call to `.mainloop()` in the `.go()` function.

I'm reluctant to add it in, as I've got no way to test it...

**Comment by abhijit-dey** [comment] 2018-01-07 03:48
I am a new programmer so sorry for asking basic questions. But I am getting the following error:
Error:
Traceback (most recent call last):
  File "test_appJar.py", line 13, in <module>
    self.topLevel.mainloop()
NameError: name 'self' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_appJar.py", line 21, in <module>
    self.exception(e)
NameError: name 'self' is not defined

The executed this:
from tkinter import *
from appJar import gui

app = gui("appJar Testing")

while True: 
            try:  
                self.topLevel.mainloop()
                app.startScrollPane("sp1")
                for x in range(0,40):
                    label_name = "l" + str(x)
                    app.addLabel(label_name, "This is inside scroll pane.")
                app.stopScrollPane()
            except(KeyboardInterrupt, SystemExit) as e: 
                self.debug("appJar stopped through ^c or exit()")
                self.stop()
                break 
            except UnicodeDecodeError:
                pass  
            except Exception as e: 
                self.exception(e)
                self.stop()
                break

**Comment by mpmc** [comment] 2018-01-07 07:23
change the self lines..
```python 
self.debug("appJar stopped through ^c or exit()")
self.stop()
```
to 
```python
app.debug("appJar stopped through ^c or exit()")
app.stop()
```

**Comment by abhijit-dey** [comment] 2018-01-07 16:19
Changed the self to app.
Executed the code.
The code starts but there is no window shown.
I have to kill the code using Ctrl+C.

**Comment by jarvisteach** [comment] 2018-03-03 18:54
Closing this as can't reproduce.

**Closed by jarvisteach** 2018-03-03 18:54 UTC
Labels: question

**Comment by cyue12** [comment] 2019-08-21 15:22
It looks like the python 3.7.3 from home brew caused the problem. I'd tried to force remove this one and Install the official python 3.7.4, seems to solve it...
